[build-system]
requires = [
    "setuptools",
    "wheel",
    "matplotlib==3.5.2",
    "pandas",
    "numpy",
    "scipy",
    "lmfit",
    "pyqt5",
    "requests",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88